### ISSUE TITLE
Maps are not displaying

### ISSUE THREAD

**Issue by CartoCoder** [Esri/map-collection-explorer#1]
![error](https://cloud.githubusercontent.com/assets/9677564/16666688/d224784a-4456-11e6-89e5-17064aae646a.jpg)
Hello, I attended an ESRI workshop on this application a few months ago so I am pretty familiar with it. To get started with a custom application I first cloned this repository to my AWS S3 web space (and after failure, my workplace server). The application opens but errors out when a users clicks on the map. I have not changed any code - just downloaded to web folder. What am I missing?

https://s3.amazonaws.com/cartocoder.com/Maps/hme_copy/index.html

**Comment by aileenbuckley** [comment]
My guess is that you’re probably running the app from a folder and not hosting it from a Web Server.  You need to run it from a web server.  Hope this helps!
