### ISSUE TITLE
Undefined values returned in renderedCell

### ISSUE THREAD

**Issue by JorritdeJongh** [Esri/map-collection-explorer#12]
Hey guys,

First of all thank you for uploading the code for this application here, it has helped me out tremendously with my application thus far. I am creating a small scale historic map application for some local archives and have been using your code as a starting point for the application. Everything thus far has been working fine, but there is one minor problem I am facing over the last 2 day or so that I don't seem to be able to find the answer to.  

Once a map is selected from the timeline (where it shows all attributes needed to be shown (name, year and citation)) it does show up in the renderedCell class in the bottom-left. Once zoomed in far enough it displays the correct thumbnail and the transparency slider.  However, the name of the map and the date of the map return undefined values. What makes it even stranger is that the downloadLink works perfectly fine and instantly downloads the correct TIF files from the server. I have tried debugging the code myself, but I get stuck to a point where the renderedCell will not show up at all. Even when I load the image server into an untouched version of the code and after I set the attribute fields to the correct field names in the image server, it also spits out undefined values. 

Are you guys able to help me sort out this problem?

Below I have pasted the results that I keep getting in the RenderedCell. I have also included a picture of the timeline hover over an object where it does show up with the right name and date of the map.

PS. I have altered the lay-out of the RenderedCell in the CSS file

<img width="272" alt="RenderedCell" src="https://user-images.githubusercontent.com/73591797/101477299-55d2a580-394f-11eb-9fb4-a25d7ef91b3c.png">
<img width="659" alt="TimelineHover" src="https://user-images.githubusercontent.com/73591797/101477300-566b3c00-394f-11eb-9943-518e425bafa7.png">

**Comment by JorritdeJongh** [comment]
I seem to have fixed the problem. It had to do with the renderedCell function retrieving the attributes from the initUrlParamData function and not from the onSelect function. By disabling the initUrlParamData function, the problem seems to have been solved and the variables for the map name and year have been assigned the correct values.

**Comment by ChrisMahlke** [comment]
@JorritdeJongh Please let me know if you encounter other issues.
