### ISSUE TITLE
February Release

### ISSUE THREAD

**Issue by sTriche** [Esri/map-collection-explorer#3]
- [x] Reordering Maps: you can only drag and reorder maps up, but cannot reorder maps down
![reorder maps](https://user-images.githubusercontent.com/6108532/52818443-a894ec00-305b-11e9-83fa-3bf29ea61650.jpg)

- [x] Internet Explorer: About icon not visible
- [x] Internet Explorer: Refresh icon not visible
- [x] Internet Explorer: 'X' is missing on the maps added to the map

- [x] Text change: From "Sign in to save maps to your ArcGIS Online account" **to** "Sign in to save a web map to your ArcGI Online account."
- [x] Update About text
- [x] Update Facebook text

- [x] Add Adobe Analytics script (script is in your email)

@ChrisMahlke 

- [x] Phil: updated the mosaic data set on PRD

**Comment by ChrisMahlke** [comment]
@sTriche Hello Stacey, I do not control how the FB window is populated with text.

**Comment by sTriche** [comment]
@ChrisMahlke is that something that we can even control what is put there or is it just how it's going to be?
