### ISSUE TITLE
Need to be able to use portal item id for basemap.  Currently the web app uses a "string" like "topo" to find

### ISSUE THREAD

**Issue by pshowalter** [Esri/map-collection-explorer#5]
Need to be able to use portal item id for basemap.  Currently the web app uses a "string" like "topo" to assign the basemap.  Would like to pick a specific portal item id.

Examples: https://www.arcgis.com/home/group.html?id=4c790318395940c18a16e8acd721de25&view=list&start=1&num=20#content

**Comment by ChrisMahlke** [comment]
This one is complete
